version: '3.1'

services:
  mysql:
    container_name: kse_mysql
    restart: always
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'test_pass'
      MYSQL_USER: 'test'
      MYSQL_PASS: 'pass'
    volumes:
      - /Users/denysbzenko/Desktop/BBB/Allergodb/mysql/mysql-server.yaml
    ports:
      - "3306:3306"
